### ISSUE TITLE
messages not appearing in browser demo, have to paste them into chat history

### ISSUE THREAD

**Issue by SAWSYSTEM** [zoan37/ChatVRM#10]
not sure if this is causing the issue with character expressions if those are supposed to work

**Comment by zoan37** [comment]
Hi! Do you have the Window AI extension installed? https://windowai.io/ (I use the OpenRouter.ai provider in Window AI extension for AI models.)

The avatar's reply should be above the input text box, or if you click on the "Conversation Log" button in the top left, it should show the conversation history.

Yes, the character expressions are supposed to work (like happy, sad, etc.).

**Comment by SAWSYSTEM** [comment]
yes, i do use window.ai, i have been trying it with cohere/command-nightly. when i click on convo log, the character's replies are empty as i said.. i think you may need to do some fixing on the web demo. edit: it does work with openrouter with the emotions as well, i just tried it. but it doesn't seem to work with together api or cohere

**Comment by zoan37** [comment]
I confirmed the issue (just got a Cohere API key, I'm seeing the response in the Window AI extension, but getting empty replies). Using OpenAI key still works though. I'll debug this, thanks! (and look into Together API as well)

**Comment by SAWSYSTEM** [comment]
thank you! good luck on the debugging, very excited to see this project make progress ^o^

**Comment by zoan37** [comment]
I deployed this fix, Cohere works now! (Problem was Cohere API doesn't support streaming, I needed to modify my code to handle non-streaming APIs). Together API is hanging for me and other window.ai apps as well (maybe my API key is too new)--will try this later.

Appreciate it, let me know if you have any feature requests / feedback! Recently I've been playing around with the beta window.ai generate3DObject API so got sidetracked, but am thinking about expanding this into NPCs in a 3D world (like can talk to multiple avatars in a room), and support full body animations. Or focus on running it locally with a bunch of customizations, like SillyTavern :)

**Comment by zoan37** [comment]
@SAWSYSTEM Does Together API work for you? I see response stuck in "Pending" in the window.ai extension for model "togethercomputer/GPT-NeoXT-Chat-Base-20B". And I see this with other apps like Chess GPT (https://play-chess-gpt.vercel.app/ ) and the demo on the window.ai website itself (https://windowai.io/ ).
